import { SelectOption } from '../Select';

export const CURRENCY_CODE_OPTIONS: SelectOption[] = [
    { label: 'ADB Unit of Account', value: 'XUA' },
    { label: 'Afghani', value: 'AFN' },
    { label: 'Algerian Dinar', value: 'DZD' },
    { label: 'Argentine Peso', value: 'ARS' },
    { label: 'Armenian Dram', value: 'AMD' },
    { label: 'Aruban Florin', value: 'AWG' },
    { label: 'Australian Dollar', value: 'AUD' },
    { label: 'Azerbaijanian Manat', value: 'AZN' },
    { label: 'Bahamian Dollar', value: 'BSD' },
    { label: 'Bahraini Dinar', value: 'BHD' },
    { label: 'Baht', value: 'THB' },
    { label: 'Balboa', value: 'PAB' },
    { label: 'Barbados Dollar', value: 'BBD' },
    { label: 'Belarussian Ruble', value: 'BYN' },
    { label: 'Belize Dollar', value: 'BZD' },
    { label: 'Bermudian Dollar', value: 'BMD' },
    { label: 'Bolivar', value: 'VEF' },
    { label: 'Boliviano', value: 'BOB' },
    { label: 'Brazilian Real', value: 'BRL' },
    { label: 'Brunei Dollar', value: 'BND' },
    { label: 'Bulgarian Lev', value: 'BGN' },
    { label: 'Burundi Franc', value: 'BIF' },
    { label: 'Cabo Verde Escudo', value: 'CVE' },
    { label: 'Canadian Dollar', value: 'CAD' },
    { label: 'Cayman Islands Dollar', value: 'KYD' },
    { label: 'CFA Franc BCEAO', value: 'XOF' },
    { label: 'CFA Franc BEAC', value: 'XAF' },
    { label: 'CFP Franc', value: 'XPF' },
    { label: 'Chilean Peso', value: 'CLP' },
    { label: 'Colombian Peso', value: 'COP' },
    { label: 'Comoro Franc', value: 'KMF' },
    { label: 'Congolese Franc', value: 'CDF' },
    { label: 'Convertible Mark', value: 'BAM' },
    { label: 'Cordoba Oro', value: 'NIO' },
    { label: 'Costa Rican Colon', value: 'CRC' },
    { label: 'Cuban Peso', value: 'CUP' },
    { label: 'Czech Koruna', value: 'CZK' },
    { label: 'Dalasi', value: 'GMD' },
    { label: 'Danish Krone', value: 'DKK' },
    { label: 'Denar', value: 'MKD' },
    { label: 'Djibouti Franc', value: 'DJF' },
    { label: 'Dobra', value: 'STN' },
    { label: 'Dominican Peso', value: 'DOP' },
    { label: 'Dong', value: 'VND' },
    { label: 'East Caribbean Dollar', value: 'XCD' },
    { label: 'Egyptian Pound', value: 'EGP' },
    { label: 'El Salvador Colon', value: 'SVC' },
    { label: 'Ethiopian Birr', value: 'ETB' },
    { label: 'Euro', value: 'EUR' },
    { label: 'Falkland Islands Pound', value: 'FKP' },
    { label: 'Fiji Dollar', value: 'FJD' },
    { label: 'Forint', value: 'HUF' },
    { label: 'Ghana Cedi', value: 'GHS' },
    { label: 'Gibraltar Pound', value: 'GIP' },
    { label: 'Gourde', value: 'HTG' },
    { label: 'Guarani', value: 'PYG' },
    { label: 'Guinea Franc', value: 'GNF' },
    { label: 'Guyana Dollar', value: 'GYD' },
    { label: 'Hong Kong Dollar', value: 'HKD' },
    { label: 'Hryvnia', value: 'UAH' },
    { label: 'Iceland Krona', value: 'ISK' },
    { label: 'Indian Rupee', value: 'INR' },
    { label: 'Iranian Rial', value: 'IRR' },
    { label: 'Iraqi Dinar', value: 'IQD' },
    { label: 'Jamaican Dollar', value: 'JMD' },
    { label: 'Jordanian Dinar', value: 'JOD' },
    { label: 'Kenyan Shilling', value: 'KES' },
    { label: 'Kina', value: 'PGK' },
    { label: 'Kip', value: 'LAK' },
    { label: 'Kuna', value: 'HRK' },
    { label: 'Kuwaiti Dinar', value: 'KWD' },
    { label: 'Kwacha', value: 'MWK' },
    { label: 'Kwanza', value: 'AOA' },
    { label: 'Kyat', value: 'MMK' },
    { label: 'Lari', value: 'GEL' },
    { label: 'Lebanese Pound', value: 'LBP' },
    { label: 'Lek', value: 'ALL' },
    { label: 'Lempira', value: 'HNL' },
    { label: 'Leone', value: 'SLL' },
    { label: 'Liberian Dollar', value: 'LRD' },
    { label: 'Libyan Dinar', value: 'LYD' },
    { label: 'Lilangeni', value: 'SZL' },
    { label: 'Loti', value: 'LSL' },
    { label: 'Malagasy Ariary', value: 'MGA' },
    { label: 'Malaysian Ringgit', value: 'MYR' },
    { label: 'Mauritius Rupee', value: 'MUR' },
    { label: 'Mexican Peso', value: 'MXN' },
    { label: 'Mexican Unidad de Inversion (UDI)', value: 'MXV' },
    { label: 'Moldovan Leu', value: 'MDL' },
    { label: 'Moroccan Dirham', value: 'MAD' },
    { label: 'Mozambique Metical', value: 'MZN' },
    { label: 'Mvdol', value: 'BOV' },
    { label: 'Naira', value: 'NGN' },
    { label: 'Nakfa', value: 'ERN' },
    { label: 'Namibia Dollar', value: 'NAD' },
    { label: 'Nepalese Rupee', value: 'NPR' },
    { label: 'Netherlands Antillean Guilder', value: 'ANG' },
    { label: 'New Israeli Sheqel', value: 'ILS' },
    { label: 'New Taiwan Dollar', value: 'TWD' },
    { label: 'New Zealand Dollar', value: 'NZD' },
    { label: 'Ngultrum', value: 'BTN' },
    { label: 'No universal currency', value: '' },
    { label: 'North Korean Won', value: 'KPW' },
    { label: 'Norwegian Krone', value: 'NOK' },
    { label: 'Nuevo Sol', value: 'PEN' },
    { label: 'Ouguiya', value: 'MRU' },
    { label: 'Pa’anga', value: 'TOP' },
    { label: 'Pakistan Rupee', value: 'PKR' },
    { label: 'Pataca', value: 'MOP' },
    { label: 'Peso Convertible', value: 'CUC' },
    { label: 'Peso Uruguayo', value: 'UYU' },
    { label: 'Philippine Peso', value: 'PHP' },
    { label: 'Pound Sterling', value: 'GBP' },
    { label: 'Pula', value: 'BWP' },
    { label: 'Qatari Rial', value: 'QAR' },
    { label: 'Quetzal', value: 'GTQ' },
    { label: 'Rand', value: 'ZAR' },
    { label: 'Rial Omani', value: 'OMR' },
    { label: 'Riel', value: 'KHR' },
    { label: 'Romanian Leu', value: 'RON' },
    { label: 'Rufiyaa', value: 'MVR' },
    { label: 'Rupiah', value: 'IDR' },
    { label: 'Russian Ruble', value: 'RUB' },
    { label: 'Rwanda Franc', value: 'RWF' },
    { label: 'Saint Helena Pound', value: 'SHP' },
    { label: 'Saudi Riyal', value: 'SAR' },
    { label: 'SDR (Special Drawing Right)', value: 'XDR' },
    { label: 'Serbian Dinar', value: 'RSD' },
    { label: 'Seychelles Rupee', value: 'SCR' },
    { label: 'Singapore Dollar', value: 'SGD' },
    { label: 'Solomon Islands Dollar', value: 'SBD' },
    { label: 'Som', value: 'KGS' },
    { label: 'Somali Shilling', value: 'SOS' },
    { label: 'Somoni', value: 'TJS' },
    { label: 'South Sudanese Pound', value: 'SSP' },
    { label: 'Sri Lanka Rupee', value: 'LKR' },
    { label: 'Sucre', value: 'XSU' },
    { label: 'Sudanese Pound', value: 'SDG' },
    { label: 'Surinam Dollar', value: 'SRD' },
    { label: 'Swedish Krona', value: 'SEK' },
    { label: 'Swiss Franc', value: 'CHF' },
    { label: 'Syrian Pound', value: 'SYP' },
    { label: 'Taka', value: 'BDT' },
    { label: 'Tala', value: 'WST' },
    { label: 'Tanzanian Shilling', value: 'TZS' },
    { label: 'Tenge', value: 'KZT' },
    { label: 'Trinidad and Tobago Dollar', value: 'TTD' },
    { label: 'Tugrik', value: 'MNT' },
    { label: 'Tunisian Dinar', value: 'TND' },
    { label: 'Turkish Lira', value: 'TRY' },
    { label: 'Turkmenistan New Manat', value: 'TMT' },
    { label: 'UAE Dirham', value: 'AED' },
    { label: 'Uganda Shilling', value: 'UGX' },
    { label: 'Unidad de Fomento', value: 'CLF' },
    { label: 'Unidad de Valor Real', value: 'COU' },
    { label: 'Uruguay Peso en Unidades Indexadas (URUIURUI)', value: 'UYI' },
    { label: 'US Dollar', value: 'USD' },
    { label: 'US Dollar (Next day)', value: 'USN' },
    { label: 'Uzbekistan Sum', value: 'UZS' },
    { label: 'Vatu', value: 'VUV' },
    { label: 'WIR Euro', value: 'CHE' },
    { label: 'WIR Franc', value: 'CHW' },
    { label: 'Won', value: 'KRW' },
    { label: 'Yemeni Rial', value: 'YER' },
    { label: 'Yen', value: 'JPY' },
    { label: 'Yuan Renminbi', value: 'CNY' },
    { label: 'Zambian Kwacha', value: 'ZMW' },
    { label: 'Zimbabwe Dollar', value: 'ZWL' },
    { label: 'Zloty', value: 'PLN' },
];
